/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brickgame;
import java.awt.Color;
import java.io.*;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.*;


/**
 *
 * @author brandonturner
 */
public class BrickGameForm extends javax.swing.JFrame {

    /**
     * Creates new form BrickGameForm
     */
    int score = 5;
    
    public BrickGameForm() {
        initComponents();
        scoreNumberLabel.setText(""+score);
        nextButton.setVisible(false);
        newGameButton.setVisible(false);
        
        numeratorLabel1.setText(""+block1Panel1.randomNumerator);
        denominatorLabel1.setText(""+(int)block1Panel1.randomImageSelect); 
        
        while((block2Panel1.randomImageSelect % block1Panel1.randomImageSelect) != 0){
            block1Panel1.newQuestion();
            block2Panel1.reset();
            
            numeratorLabel1.setText(""+block1Panel1.randomNumerator);
            denominatorLabel1.setText(""+(int)block1Panel1.randomImageSelect);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equivalentButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        scoreNumberLabel = new javax.swing.JLabel();
        block1Panel1 = new brickgame.Block1Panel();
        block2Panel1 = new brickgame.Block2Panel();
        userMessage = new javax.swing.JLabel();
        numeratorLabel1 = new javax.swing.JLabel();
        denominatorLabel1 = new javax.swing.JLabel();
        numeratorLabel2 = new javax.swing.JLabel();
        denominatorLabel2 = new javax.swing.JLabel();
        divider1 = new javax.swing.JLabel();
        divider2 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        minusButton = new javax.swing.JLabel();
        plusButton = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(609, 400));
        setMinimumSize(new java.awt.Dimension(609, 400));
        setPreferredSize(new java.awt.Dimension(609, 400));
        getContentPane().setLayout(null);

        equivalentButton.setText("Equivalent!");
        equivalentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equivalentButtonMouseClicked(evt);
            }
        });
        getContentPane().add(equivalentButton);
        equivalentButton.setBounds(470, 320, 120, 23);

        scoreLabel.setText("Score :");
        getContentPane().add(scoreLabel);
        scoreLabel.setBounds(480, 10, 50, 14);

        scoreNumberLabel.setText("0");
        getContentPane().add(scoreNumberLabel);
        scoreNumberLabel.setBounds(523, 11, 50, 14);

        block1Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                block1Panel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout block1Panel1Layout = new javax.swing.GroupLayout(block1Panel1);
        block1Panel1.setLayout(block1Panel1Layout);
        block1Panel1Layout.setHorizontalGroup(
            block1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        block1Panel1Layout.setVerticalGroup(
            block1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(block1Panel1);
        block1Panel1.setBounds(150, 80, 250, 50);

        block2Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                block2Panel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout block2Panel1Layout = new javax.swing.GroupLayout(block2Panel1);
        block2Panel1.setLayout(block2Panel1Layout);
        block2Panel1Layout.setHorizontalGroup(
            block2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        block2Panel1Layout.setVerticalGroup(
            block2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(block2Panel1);
        block2Panel1.setBounds(150, 200, 250, 50);

        userMessage.setForeground(new java.awt.Color(255, 51, 51));
        userMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(userMessage);
        userMessage.setBounds(150, 30, 250, 20);
        getContentPane().add(numeratorLabel1);
        numeratorLabel1.setBounds(450, 90, 45, 16);
        getContentPane().add(denominatorLabel1);
        denominatorLabel1.setBounds(450, 110, 40, 20);
        getContentPane().add(numeratorLabel2);
        numeratorLabel2.setBounds(450, 200, 45, 20);
        getContentPane().add(denominatorLabel2);
        denominatorLabel2.setBounds(450, 230, 40, 20);

        divider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/divider.png"))); // NOI18N
        getContentPane().add(divider1);
        divider1.setBounds(440, 100, 34, 14);

        divider2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/divider.png"))); // NOI18N
        getContentPane().add(divider2);
        divider2.setBounds(440, 220, 34, 14);

        nextButton.setText("Next Question!");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(470, 320, 120, 23);

        minusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/minus.png"))); // NOI18N
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });
        getContentPane().add(minusButton);
        minusButton.setBounds(100, 220, 45, 16);

        plusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus.png"))); // NOI18N
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusButtonMouseClicked(evt);
            }
        });
        getContentPane().add(plusButton);
        plusButton.setBounds(40, 210, 40, 40);

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newGameButton);
        newGameButton.setBounds(470, 320, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void block1Panel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_block1Panel1KeyPressed
        
    }//GEN-LAST:event_block1Panel1KeyPressed

    private void block1Panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_block1Panel1MouseClicked

    }//GEN-LAST:event_block1Panel1MouseClicked

    private void block2Panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_block2Panel1MouseClicked
       block2Panel1.nextImage();
       numeratorLabel2.setText(""+block2Panel1.counter);
       denominatorLabel2.setText(""+(int)block2Panel1.randomImageSelect);
    }//GEN-LAST:event_block2Panel1MouseClicked

    private void equivalentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equivalentButtonMouseClicked
      if(block1Panel1.answer == block2Panel1.answer){
          System.out.println("You got it right!");
          userMessage.setForeground(Color.green);
          userMessage.setText("Good Job!");
          //playMath();
          score++;
          scoreNumberLabel.setText(""+score);
          equivalentButton.setVisible(false);
          nextButton.setVisible(true);
          if(score == 10){
              userMessage.setText("YOU WIN!");
              nextButton.setVisible(false);
              newGameButton.setVisible(true);
          }
          
          
      }
      else{
          System.out.println("Nerd you got it wrong");
          score--;
          userMessage.setForeground(Color.red);
          userMessage.setText("Try Again");
          scoreNumberLabel.setText(""+score);
      }
    }//GEN-LAST:event_equivalentButtonMouseClicked

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        userMessage.setText("");
        nextButton.setVisible(false);
        equivalentButton.setVisible(true);
        
        block1Panel1.newQuestion();
        
        numeratorLabel1.setText(""+block1Panel1.randomNumerator);
        denominatorLabel1.setText(""+(int)block1Panel1.randomImageSelect);
        
        block2Panel1.reset();
        numeratorLabel2.setText(""+block2Panel1.counter);
        denominatorLabel2.setText(""+(int)block2Panel1.randomImageSelect);
        
        while((block2Panel1.randomImageSelect % block1Panel1.randomImageSelect) != 0){
            block1Panel1.newQuestion();
            block2Panel1.reset();
            
            numeratorLabel1.setText(""+block1Panel1.randomNumerator);
            denominatorLabel1.setText(""+(int)block1Panel1.randomImageSelect);
        }
        
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void plusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseClicked
       block2Panel1.nextImage();
       numeratorLabel2.setText(""+block2Panel1.counter);
       denominatorLabel2.setText(""+(int)block2Panel1.randomImageSelect);
    }//GEN-LAST:event_plusButtonMouseClicked

    private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked
       block2Panel1.previousImage();
       numeratorLabel2.setText(""+block2Panel1.counter);
       denominatorLabel2.setText(""+(int)block2Panel1.randomImageSelect);
    }//GEN-LAST:event_minusButtonMouseClicked

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        score = 0;
        scoreNumberLabel.setText(""+score);
        nextButton.setVisible(false);
        newGameButton.setVisible(false);
        
        block1Panel1.newQuestion();
        
        numeratorLabel1.setText(""+block1Panel1.randomNumerator);
        denominatorLabel1.setText(""+(int)block1Panel1.randomImageSelect);
        
        block2Panel1.reset();
        numeratorLabel2.setText(""+block2Panel1.counter);
        denominatorLabel2.setText(""+(int)block2Panel1.randomImageSelect);
        
        while((block2Panel1.randomImageSelect % block1Panel1.randomImageSelect) != 0){
            block1Panel1.newQuestion();
            block2Panel1.reset();
            
            numeratorLabel1.setText(""+block1Panel1.randomNumerator);
            denominatorLabel1.setText(""+(int)block1Panel1.randomImageSelect);
        }
    }//GEN-LAST:event_newGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrickGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrickGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrickGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrickGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrickGameForm().setVisible(true);
            }
        });
        
        
    }
    public void playMath(){
        try{
          File file = new File("/resources/math.mp3");
          FileInputStream fis = new FileInputStream(file);
          BufferedInputStream bis = new BufferedInputStream(fis);
          
          try{
              Player player = new Player(bis);
              player.play();
          }
          catch(JavaLayerException ex){
              
          }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private brickgame.Block1Panel block1Panel1;
    private brickgame.Block2Panel block2Panel1;
    private javax.swing.JLabel denominatorLabel1;
    private javax.swing.JLabel denominatorLabel2;
    private javax.swing.JLabel divider1;
    private javax.swing.JLabel divider2;
    private javax.swing.JButton equivalentButton;
    private javax.swing.JLabel minusButton;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel numeratorLabel1;
    private javax.swing.JLabel numeratorLabel2;
    private javax.swing.JLabel plusButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreNumberLabel;
    private javax.swing.JLabel userMessage;
    // End of variables declaration//GEN-END:variables
}
